import smtplib
from email.mime.text import MIMEText

# Configuration
port = 587
smtp_server = "smtp.gmail.com"
login = "trung01694@gmail.com"  # Your login generated by Mailtrap
password = "schx hzeq pqwr dnyq"  # Your password generated by Mailtrap

sender_email = "trung01694@example.com"
receiver_email = "huytqd@gmail.com"

# Plain text content
text = """\
Hi,
huy lỏ làm chi đây
"""

# Create MIMEText object
message = MIMEText(text, "plain")
message["Subject"] = "Plain text email"
message["From"] = sender_email
message["To"] = receiver_email

# Send the email
with smtplib.SMTP(smtp_server, port) as server:
    server.starttls()  # Secure the connection
    server.login(login, password)
    server.sendmail(sender_email, receiver_email, message.as_string())

print('Sent')